checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  dirpath: checkpoints/classifier/cs${experiment.train_classifier.datamodule.label}
  filename: placeholder
  save_top_k: 1
  save_weights_only: true
  mode: min
